[build]
  publish = "public"

# Handle all routes by serving index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Serve APK file with correct MIME type
[[headers]]
  for = "/*.apk"
  [headers.values]
    Content-Disposition = "attachment"
    Content-Type = "application/vnd.android.package-archive"
# URL - Your dummy site URL
