[build]
  command = ""
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
# Development environment overrides
[context.develop.environment]
  NODE_ENV = "development"

# Deploy preview environment overrides
[context.deploy-preview.environment]
  NODE_ENV = "preview"
# NETLIFY_ACCESS_TOKEN - Your Netlify API token
# GITHUB_REPO - Repository to deploy (e.g., "hardikdesai6774-art/hardik_download")  
# GITHUB_BRANCH - Branch to deploy (default: "main")
# URL - Your dummy site URL
