[build]
  command = "echo 'No build step needed for static site'"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = false

[[edge_functions]]
  function = "redirect"
  path = "/*"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Enable KV store for state management
[functions.rotation-status]
  kv = "rotation-kv-store"

[functions.update-rotation]
  kv = "rotation-kv-store"

[functions.rotate-site]
  kv = "rotation-kv-store"
  schedule = "0 */4 * * *"  # Run every 4 hours

[build.environment]
  NODE_VERSION = "20"

# Required environment variables for the rotation system
[context.production.environment]
  STABLE_URL = "https://kaveri-mallu.netlify.app"
  # These will be stored in KV store:
  # - CURRENT_SITE_URL
  # - CURRENT_SITE_ID
  # - LAST_ROTATION
  # - NETLIFY_ACCESS_TOKEN (set in Netlify dashboard)

# Development environment overrides
[context.develop.environment]
  NODE_ENV = "development"

# Deploy preview environment overrides
[context.deploy-preview.environment]
  NODE_ENV = "preview"
# NETLIFY_ACCESS_TOKEN - Your Netlify API token
# GITHUB_REPO - Repository to deploy (e.g., "hardikdesai6774-art/hardik_download")  
# GITHUB_BRANCH - Branch to deploy (default: "main")
# URL - Your dummy site URL
